/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "openhevc-2.0-158-g4dc7869"
#endif /* AVUTIL_FFVERSION_H */
