/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "openhevc-1.0-9-g2a15d76"
#endif /* AVUTIL_FFVERSION_H */
