/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ffmpeg-2.5-533-gcbe0a76"
#endif /* AVUTIL_FFVERSION_H */
