include $(SUBDIR)../config.mak

NAME = openhevc

HEADERS = openHevcWrapper.h                             \
          version.h                                     \

OBJS = openHevcWrapper.o                                \

# Windows resource file
SLIBOBJS-$(HAVE_GNU_WINDRES) += openHevcWrapper.o