NAME = openhevc
DESC = OpenHEVC Decoder

HEADERS = openhevc.h                             \
          version.h                              \
          config.h

OBJS = openhevc.o                                \

# Windows resource file
SLIBOBJS-$(HAVE_GNU_WINDRES) += openhevc.o
